[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.venv
  | build
  | dist
)/
'''
