# Generated by Django 5.2.5 on 2025-09-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("character_data", models.JSONField(default=dict)),
                ("consecutive_wins", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("damage", models.IntegerField()),
                (
                    "damage_type",
                    models.CharField(
                        choices=[
                            ("slashing", "Рубящий"),
                            ("bludgeoning", "Дробящий"),
                            ("piercing", "Колющий"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("health", models.IntegerField()),
                ("weapon_damage", models.IntegerField()),
                ("strength", models.IntegerField()),
                ("agility", models.IntegerField()),
                ("endurance", models.IntegerField()),
                ("features", models.TextField(blank=True)),
                (
                    "reward_weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.weapon"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("health_per_level", models.IntegerField()),
                ("level1_bonus", models.TextField()),
                ("level2_bonus", models.TextField()),
                ("level3_bonus", models.TextField()),
                (
                    "initial_weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.weapon"
                    ),
                ),
            ],
        ),
    ]
