# Generated by Django 5.2.5 on 2025-09-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='features',
            new_name='special_ability',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='character_data',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='consecutive_wins',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='damage_type',
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(
                choices=[
                    ('slashing', 'Рубящий'),
                    ('crushing', 'Дробящий'),
                    ('piercing', 'Колющий'),
                ],
                default='unknown',
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('battle_number', models.IntegerField()),
                ('log_data', models.TextField()),
                ('winner', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'game_session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='game.gamesession'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('strength', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('rogue_level', models.IntegerField(default=0)),
                ('warrior_level', models.IntegerField(default=0)),
                ('barbarian_level', models.IntegerField(default=0)),
                ('current_health', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('monsters_defeated', models.IntegerField(default=0)),
                ('total_level', models.IntegerField(default=1)),
                (
                    'current_weapon',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='game.weapon'
                    ),
                ),
                (
                    'game_session',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='game.gamesession'
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='CharacterClass',
        ),
    ]
